apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "load-tester.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.redis.host | quote }}
  port: {{ .Values.redis.port | quote }}
  password: {{ .Values.redis.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: servicebus-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "load-tester.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: {{ .Values.serviceBus.connectionString | quote }}
